name: .Net workflow test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:7.0
      ports:
        - 5135
        - 7135
      volumes:
        - my_docker_volume:/volume_mount
      options: --cpus 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Restore Dependencies
        run: dotnet restore CardValidation.sln

      - name: Build Solution
        run: dotnet build CardValidation.sln --configuration Release --no-restore

      - name: Create results directory
        run: mkdir -p results

      - name: Run Unit Tests
        run: |
          dotnet test ./CardValidation.CoreTests/CardValidation.CoreTests.csproj \
            --configuration Release \
            --no-build \
            --logger "trx;LogFileName=unit_tests.trx"
              --verbosity detailed # Adding detailed verbosity
            ls -al # List all files in the current directory to verify the .trx file exists
             mv ./unit_tests.trx results/ # Move the file to results directory

      - name: Start API Server in Background
        run: |
          cd CardValidation.Web
          nohup dotnet run --no-build \
                           --configuration Release \
                           --urls "http://0.0.0.0:7135" \
                           > /dev/null 2>&1 &
          sleep 10

      - name: Run Integration Tests
        continue-on-error: true
        run: |
          dotnet test ./CardValidation.Core/CardValidation.Core.csproj \
            --configuration Release \
            --no-build \
            --logger "trx;LogFileName=integration_tests.trx"
            mv *.trx results/
          

      - name: Convert TRX to HTML with ReportGenerator
        if: always()
        run: |
            ls -a results  
            dotnet tool install --global dotnet-reportgenerator-globaltool --version 5.2.2
            export PATH="$PATH:/github/home/.dotnet/tools" 
            
            reportgenerator \
            -reports:results/unit_tests.trx \
            -targetdir:results/report \
            -reporttypes:Html

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-test-results
          path: | 
              results/*.trx
              results/report/**/*.html