name: .Net workflow test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:7.0
      ports:
        - 5135
        - 7135
      volumes:
        - my_docker_volume:/volume_mount
      options: --cpus 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Restore Dependencies
        run: dotnet restore CardValidation.sln

      - name: Build Solution
        run: dotnet build CardValidation.sln --configuration Release --no-restore

      - name: Run Unit Tests
        run: |
          dotnet test ./CardValidation.CoreTests/CardValidation.CoreTests.csproj \
            --configuration Release \
            --no-build \
            --logger "trx;LogFileName=unit_tests.trx"

      - name: Start API Server in Background
        run: |
          cd CardValidation.Web
          nohup dotnet run --no-build \
                           --configuration Release \
                           --urls "http://0.0.0.0:7135" \
                           > /dev/null 2>&1 &
          sleep 10

      - name: Run Integration Tests
        run: |
          dotnet test ./CardValidation.Core/CardValidation.Core.csproj \
            --configuration Release \
            --no-build \
            --logger "trx;LogFileName=integration_tests.trx"

      - name: Convert TRX to HTML
        run: |
          dotnet tool install --global trx2html
          trx2html unit_tests.trx -o UnitTestResults.html
          trx2html integration_tests.trx -o IntegrationTestResults.html

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-test-results
          path: | 
              **/.trx
              **/*.html