name: .Net workflow test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build --no-cache -f ./Dockerfile -t card-validation-tests .

      - name: Run unit tests
        run: docker run --rm card-validation-tests

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: test results
          path: ./test-*.xml