name: .Net workflow test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build --no-cache -f ./DockerFile -t card-validation-tests .

      - name: Run unit tests
        run: docker run -d --network=host card-validation-tests --command "dotnet test CardValidation.CoreTests/CardValidation.CoreTests.csproj --logger:trx"

      - name: Start API server 
        run: |
           docker run -d --name api-server --network=host card-validation-tests
            sleep 15
            docker ps -a

            echo "API server is up and running!"


      - name: Run integration tests
        run:  docker run --network=host -d card-validation-tests --command "dotnet test /app/CardValidation.Core/CardValidation.Core.csproj --logger:trx"

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: test results
          path: ./test-*.xml



