name: .Net workflow test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build --no-cache -f ./DockerFile -t card-validation-tests .

      - name: Run unit tests
        run: docker run --rm card-validation-tests dotnet test /app/CardValidation.CoreTests/CardValidation.CoreTests.csproj --logger:trx

      - name: Start API server 
        run: |
               # Run the API server container in detached mode
                docker run -d -p 8080:5135 card-validation-tests dotnet run --project /app/CardValidation.Web/CardValidation.Web.csproj --urls http://0.0.0.0:8080

                # Wait for the API server to be available on port 5135
                docker run --rm jwilder/dockerize -wait http://localhost:8080 -timeout 300s
          
                # Verify if server is accessible after waiting
                echo "API server is up and running!"


      - name: Run integration tests
        run: docker run --rm card-validation-tests dotnet test /app/CardValidation.Core/CardValidation.Core.csproj --logger:trx

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: test results
          path: ./test-*.xml



