name: .Net workflow test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:7.0
      ports:
        - 5135
        - 7135
      volumes:
        - my_docker_volume:/volume_mount
      options: --cpus 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Unit Tests
        run: |
          ls -a
          dotnet test ./CardValidation.CoreTests/CardValidation.CoreTests.csproj --logger:trx

      - name: Start API Server
        run: |
          dotnet run ./CardValidation.Web
          sleep 15 

      - name: Run Integration Tests
        run: |
          dotnet test ./CardValidation.Core/CardValidation.Core.csproj --logger:trx

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
            name: dotnet-test-results
            path: dotnet-test-results