name: .Net workflow test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build --no-cache -f ./DockerFile -t card-validation-tests .

      - name: Run Unit Tests
        run: |
          docker run --rm card-validation-tests dotnet test /app/CardValidation.CoreTests/CardValidation.CoreTests.csproj --logger:trx

      - name: Start API Server in Container
        run: |
          docker run -d  -p 5135:5135 -p 7135:7135 --name api-server --network=host card-validation-tests
          sleep 15 
          docker ps -a

      - name: Run Integration Tests
        run: |
          docker run --network=host --rm card-validation-tests dotnet test /app/CardValidation.Core/CardValidation.Core.csproj --logger:trx

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
            name: dotnet-test-results
            path: dotnet-test-results

      - name: Stop and Remove API Server
        run: docker stop api-server && docker rm api-server